# Add binaries into the path
# PATH=~/.dotfiles/bin:$PATH
# export PATH

# Source all files in ~/.source/
function src() {
  local file
  if [[ "$1" ]]; then
    source "$HOME/.source/$1.sh"
  else
    for file in ~/.source/*.sh; do
      source "$file"
    done
    if [ -f ~/.bashrc.local ]; then
        source ~/.bashrc.local
    fi
  fi
}

# Run homebase script, then source.
function homebase() {
  ~/homebase/homebase "$@" && src
}

src
