set nocompatible " be iMproved
filetype off " required

if executable("powerline-daemon") && has("python")
    python from powerline.vim import setup as powerline_setup
    python powerline_setup()
    python del powerline_setup
endif

if isdirectory(expand("~/.vim/bundle/vundle/"))
    set rtp+=~/.vim/bundle/vundle/
    call vundle#rc()

    Bundle 'gmarik/vundle'
    Bundle 'tpope/vim-fugitive'
    Bundle 'tpope/vim-sensible'
    Bundle 'tpope/vim-markdown'
    Bundle 'nvie/vim-flake8'
    " Bundle 'git://git.wincent.com/command-t.git'
    " Bundle 'vim-scripts/jslint.vim'
    Bundle 'kien/ctrlp.vim'
    Bundle 'epmatsw/ag.vim'
    Bundle 'Valloric/YouCompleteMe'
    Bundle 'Lokaltog/vim-easymotion'
    Bundle 'scrooloose/syntastic'

    " colors
    Bundle 'vim-scripts/vividchalk.vim'
    Bundle 'sickill/vim-monokai'
    Bundle 'altercation/vim-colors-solarized'
endif

filetype plugin indent on
syntax on

" On by default, turn it off for html
let g:syntastic_mode_map = { 'mode': 'active',
        \ 'active_filetypes': [],
        \ 'passive_filetypes': ['html'] }

let g:syntastic_python_checkers = ['flake8']
let g:syntastic_python_flake8_args = '--ignore="E501,E302,E261,E701,E241,E126,E127,E128,W293,W801"'

" Use jshint (uses ~/.jshintrc)
let g:syntastic_javascript_checkers = ['jshint']
 
" Better :sign interface symbols
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '!'

set background=dark
silent! colors monokai

set number " line numbers
set ts=4 " tab stop
set sw=4 " shift width
set sts=4 " soft tab stop
set expandtab " tabs to spaces
 
set backspace=indent,eol,start

set splitright
set splitbelow
 
set autoindent
set showcmd
set showmatch " highlight matching brackets
